// ממפה שם יצרן (עברית/אנגלית) לסלאג ב-avto-dev CDN
// https://github.com/avto-dev/vehicle-logotypes

const LOGO_MAP: Record<string, string> = {
  // עברית
  "טויוטה": "toyota",
  "הונדה": "honda",
  "מזדה": "mazda",
  "מיצובישי": "mitsubishi",
  "סובארו": "subaru",
  "ניסאן": "nissan",
  "יונדאי": "hyundai",
  "קיה": "kia",
  "שברולט": "chevrolet",
  "פולקסווגן": "volkswagen",
  "סקודה": "skoda",
  "סיאט": "seat",
  "אאודי": "audi",
  "מרצדס בנץ": "mercedes-benz",
  "מרצדס": "mercedes-benz",
  "ב.מ.וו": "bmw",
  "BMW": "bmw",
  "פורד": "ford",
  "אופל": "opel",
  "פיג'ו": "peugeot",
  "ציטרואן": "citroen",
  "רנו": "renault",
  "פיאט": "fiat",
  "אלפא רומיאו": "alfa-romeo",
  "וולוו": "volvo",
  "סאאב": "saab",
  "סוזוקי": "suzuki",
  "דייהטסו": "daihatsu",
  "לקסוס": "lexus",
  "אינפיניטי": "infiniti",
  "אקורה": "acura",
  "קאדילק": "cadillac",
  "ג'יפ": "jeep",
  "דודג'": "dodge",
  "ג'י.אמ.סי": "gmc",
  "לנד רובר": "land-rover",
  "ג'גואר": "jaguar",
  "פורשה": "porsche",
  "מיני": "mini",
  "סמארט": "smart",
  "טסלה": "tesla",
  "ב.י.ד": "byd",
  "BYD": "byd",
  "MG": "mg",
  // אנגלית (fallback)
  "toyota": "toyota",
  "honda": "honda",
  "mazda": "mazda",
  "mitsubishi": "mitsubishi",
  "subaru": "subaru",
  "nissan": "nissan",
  "hyundai": "hyundai",
  "kia": "kia",
  "volkswagen": "volkswagen",
  "skoda": "skoda",
  "seat": "seat",
  "audi": "audi",
  "ford": "ford",
  "opel": "opel",
  "peugeot": "peugeot",
  "citroen": "citroen",
  "renault": "renault",
  "fiat": "fiat",
  "volvo": "volvo",
  "suzuki": "suzuki",
  "lexus": "lexus",
  "jeep": "jeep",
  "tesla": "tesla",
};

export function getManufacturerSlug(name: string): string {
  if (!name) return "";
  const lower = name.toLowerCase().trim();
  return LOGO_MAP[name] ?? LOGO_MAP[lower] ?? lower.replace(/\s+/g, "-");
}
